POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "ftoro-ca2",
    "name": "Felipe Toro",
    "password": "secreto"
}

###

POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "ftoro-ca5",
    "name": "Felipe Toro",
    "password": "LapipePassword"
}